import numpy as np
print('join two 1D arrays using concatenate attribute')
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr=np.concatenate((arr1 , arr2))
print(arr)
print()
print('using two 1D array to get  2D array using stack')
arr3=np.array([1,2,3,4])
arr4=np.array([5,6,7,8])
arr5=np.stack((arr3, arr4))
print(arr5)
print()
print('using two 1D array to get  2D array using stack')
arr6=np.array([1,2])
arr7=np.array([5,6])
arr8=np.hstack((arr6,arr7))
print(arr8)

