import numpy as np
print('sort method on array list')
arr=np.array([2,5,4,6,3,1])
print(np.sort(arr))
print(' sort method used on strings')
arr1 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr1))
print('sort method used on boolean data type')
arr2 = np.array([True, False, True])
print(np.sort(arr2))